/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#001430',
        'primary-container': '#002855',
        'on-primary': '#ffffff',
        'on-primary-container': '#7490c3',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#aac7fd',
        'on-primary-fixed': '#001b3d',
        'on-primary-fixed-variant': '#284775',
        surface: '#f7f9fc',
        'surface-dim': '#d8dadd',
        'surface-bright': '#f7f9fc',
        'surface-lowest': '#ffffff',
        'surface-low': '#f2f4f7',
        'surface-container': '#eceef1',
        'surface-high': '#e6e8eb',
        'surface-highest': '#e0e3e6',
        'on-surface': '#191c1e',
        'on-surface-variant': '#43474f',
        tertiary: '#1c1300',
        'tertiary-container': '#362600',
        'tertiary-fixed': '#ffdf9c',
        'tertiary-fixed-dim': '#e2c382',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#a78c51',
        'on-tertiary-fixed': '#251a00',
        'on-tertiary-fixed-variant': '#59440f',
        secondary: '#5c5f62',
        'secondary-container': '#e0e3e6',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#626568',
        outline: '#747780',
        'outline-variant': '#c4c6d0',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        headline: ['Public Sans', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'xs': '0.125rem',
        'sm': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
      },
      boxShadow: {
        'ambient': '0 8px 32px 0 rgba(0, 20, 48, 0.06)',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
